version: 1.2.{build}
image: Visual Studio 2017
install:
- cmd: >-
    git submodule update --init --recursive

    nuget restore
before_build:
- cmd: >-
    dotnet sln remove iTunesNPPlugin\iTunesNPPlugin.csproj
    
    dotnet sln remove NowPlaying4Mac\NowPlaying4Mac.csproj
build:
  project: NowPlayingV2.sln
  parallel: true
  verbosity: minimal
test:
  categories:
    except:
      - PluginTest
